version: "3.2"
services:
  sql:
    image: sql-express
    ports:
      - "1433:1433"
    networks:
      - webnet
  rendering:
    image: umbraco-admin
    ports:
      - "8000:8000"
    networks:
      - webnet
networks:
  webnet:
